- name: Allow 'vagrant' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%vagrant'
    line: '%vagrant ALL=(ALL) NOPASSWD: ALL'
  tags: [common]

- name: Dependencies are present
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ dependencies }}"
  tags: [common]

- name: Host is present
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ item.host_ip }}"
    line: "{{ item.host_ip }} {{ item.host_name }}"
  with_items: "{{ hostnames }}"
  tags: [common]
