- name: Directories are created
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ global_user }}"
    mode: "{{ item.mode }}"
  with_items: "{{ directories }}"
  tags: [docker]

- name: Dependencies are present
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ dependencies }}"
  tags: [common]

- name: files are copied
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ files }}"
  register: copy_files
  tags: [docker]

# - name: "docker-py {{ docker_py_version }} is present"
- name: Python dependencies are satisfied
  pip:
    requirements: "{{ role_path }}/files/pip-requirements.txt"
  tags: [docker, python]

- name: daemon is reloaded
  command: systemctl daemon-reload
  when: copy_files|changed
  tags: [docker]

- name: docker service is restarted
  service:
    name: docker
    state: restarted
    enabled: yes
  when: copy_files|changed
  tags: [docker, restart]

- name: docker service is present
  service:
    name: docker
    enabled: yes
    state: started
  tags: [docker]
